# Generated by Django 6.0.2 on 2026-03-02 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('enterprise', 'Enterprise')], default='basico', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_kpi', models.CharField(max_length=50)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('umbral_sensibilidad', models.FloatField(default=20.0)),
                ('activa', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_kpi', models.CharField(max_length=50)),
                ('valor_detectado', models.FloatField()),
                ('valor_esperado', models.FloatField()),
                ('desviacion', models.FloatField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('mensaje', models.TextField()),
                ('recomendacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('revisada', 'Revisada'), ('resuelta', 'Resuelta')], default='activa', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.clinica')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='core.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('primera_visita', models.DateField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_agendada', models.DateTimeField()),
                ('fecha_hora_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show'), ('reagendada', 'Reagendada')], default='agendada', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('ingreso_generado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.clinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tasa_cancelacion', 'Tasa de Cancelación'), ('tasa_noshow', 'Tasa de No Show'), ('ocupacion_agenda', 'Ocupación de Agenda'), ('tiempo_espera', 'Tiempo Promedio de Espera'), ('ingresos_dia', 'Ingresos por Día'), ('ticket_promedio', 'Ticket Promedio'), ('pacientes_nuevos', 'Pacientes Nuevos vs Recurrentes'), ('retencion_90', 'Retención a 90 Días'), ('cancelaciones_medico', 'Cancelaciones por Médico'), ('citas_reagendadas', 'Citas Reagendadas')], max_length=50)),
                ('valor', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes')], default='dia', max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.clinica')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='core.medico')),
            ],
        ),
    ]
