# Generated by Django 6.0.3 on 2026-03-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrokpi',
            name='tipo',
            field=models.CharField(choices=[('tasa_cancelacion', 'Tasa de Cancelación'), ('tasa_noshow', 'Tasa de No Show'), ('ocupacion_agenda', 'Ocupación de Agenda'), ('tiempo_espera', 'Tiempo Promedio de Espera'), ('ingresos_dia', 'Ingresos por Día'), ('ticket_promedio', 'Ticket Promedio'), ('pacientes_nuevos', 'Pacientes Nuevos vs Recurrentes'), ('retencion_90', 'Retención a 90 Días'), ('cancelaciones_medico', 'Cancelaciones por Médico'), ('citas_reagendadas', 'Citas Reagendadas'), ('nps', 'Net Promoter Score')], max_length=50),
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='core.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='IntegracionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('doctoralia', 'Doctoralia'), ('odoo', 'Odoo'), ('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('csv', 'CSV Manual')], max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_url', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('error', 'Error')], default='activa', max_length=20)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('prueba', 'Prueba')], default='prueba', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_renovacion', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_facturacion', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='core.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='alerta',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='core.sede'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.sede'),
        ),
        migrations.AddField(
            model_name='medico',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='core.sede'),
        ),
        migrations.AddField(
            model_name='registrokpi',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='core.sede'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('registros_importados', models.IntegerField(default=0)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_detalle', models.TextField(blank=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.integracionexterna')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('viewer', 'Visualizador')], default='admin', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.clinica')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('destinatario', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_util', models.BooleanField()),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.usuario')),
            ],
        ),
    ]
