# Generated by Django 6.0.3 on 2026-03-30 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrokpi_tipo_encuesta_integracionexterna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_notificacion', to='core.clinica')),
            ],
            options={
                'unique_together': {('clinica', 'email')},
            },
        ),
    ]
