# Generated by Django 6.0.3 on 2026-03-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailnotificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='foto_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='core.usuario'),
        ),
    ]
