# Generated by Django 6.0.3 on 2026-03-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medico_descripcion_medico_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_url',
            field=models.TextField(blank=True),
        ),
    ]
