# Generated by Django 6.0.3 on 2026-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medico_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='metodo_deteccion',
            field=models.CharField(default='estadistico', help_text='Metodo que detecto la anomalia: estadistico, prophet, pyod, ensemble:...', max_length=50),
        ),
    ]
