# Generated by Django 6.0.3 on 2026-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alerta_metodo_deteccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='detalle_deteccion',
            field=models.JSONField(blank=True, default=dict, help_text='Resultados individuales de cada método de detección'),
        ),
    ]
