# Generated by Django 6.0.3 on 2026-04-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_detalle_deteccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='claude_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='motor_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinica',
            name='motor_intervalo_horas',
            field=models.IntegerField(choices=[(1, '1 hora'), (6, '6 horas'), (12, '12 horas'), (24, '24 horas')], default=1),
        ),
        migrations.AddField(
            model_name='clinica',
            name='ultimo_motor_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
