# Generated by Django 6.0.3 on 2026-04-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clinica_motor_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
