# Generated by Django 6.0.3 on 2026-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clinica_whatsapp_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('viewer', 'Visualizador')], default='admin', max_length=20),
        ),
    ]
