# Generated by Django 6.0.3 on 2026-04-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_gerente_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('medico', 'Personal Médico'), ('viewer', 'Visualizador')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_solicitado', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('medico', 'Personal Médico'), ('viewer', 'Visualizador')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to='core.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_rol', to='core.usuario')),
            ],
        ),
    ]
