# Generated by Django 6.0.3 on 2026-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_sede_paciente_usuario_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='generador_activo',
            field=models.BooleanField(default=True),
        ),
    ]
