# Generated by Django 6.0.3 on 2026-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_generador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
