# Generated by Django 6.0.3 on 2026-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_avatar_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
