# Generated by Django 6.0.3 on 2026-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paciente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfacturacion',
            name='marca_tarjeta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='planfacturacion',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='planfacturacion',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='planfacturacion',
            name='ultimos_cuatro',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
